#!/usr/bin/env node

'use strict';

// Pandoc filter for DEP-non-null.
//
// Handles:
// - Special "links" for ins/del.
// - Format "Comment" as \sf.

var pandoc = require('pandoc-filter');
var Str = pandoc.Str;
var optMd = process.argv.length > 2 && process.argv[2] === '--md';

if (typeof String.prototype.startsWith != 'function') {
  // see below for better implementation!
  String.prototype.startsWith = function (str){
    return this.indexOf(str) === 0;
  };
}

function isDssChangeCmd(type, value, str) {
    // Link([Inline], Target)
    // Target = [URL,title]
    
    var linkTarget = value[1];
    if (type !== 'Link' || !linkTarget || linkTarget.length < 2)
        return false;

    return linkTarget[1].startsWith(str);
}

function action(type, value, format, meta) {
    if (isDssChangeCmd(type, value, 'INS:')) {
        var list = value[0].slice();
        list.unshift(Str("[["));
        list.push(Str("]]"));
        return pandoc.Link(list, value[1]);
    }

    if (isDssChangeCmd(type, value, 'DEL:'))
        return pandoc.Strikeout(value[0]);

    if (type === 'Str'
        && (value.startsWith('Comment.') || value.startsWith('Comments:')) ) {
        return [ pandoc.RawInline('tex','\\sf{}'), Str(value) ];
    }

    // Dart syntax highlighting isn't supported; use Java instead.
    if (type === 'CodeBlock') {
        var codeStyle = value[0][1][0];
        if (codeStyle !== 'dart') return;

        var attr = value[0].slice();
        var code = value[1];
        var codeStyleEtc = attr[1].slice();
        codeStyleEtc[0] = 'java';
        attr[1] = codeStyleEtc;
        return pandoc.CodeBlock(attr, code);
    }

    // Ensure custom header ids get embedded into generated markdown
    if (type === 'Header' && value[1].length > 0) {
        var name = value[1][0];
        return [
            pandoc.RawBlock('html','<a name="' + name + '"></a>'),
            pandoc.Header(value[0], value[1], value[2])
        ];
    }
    
    if (optMd && type === 'Math') {
        var mathText = value[1]
            .replace(/\\cd{([^}]+)}/g, '$1')
            .replace(/\\bot\b/g, '⊥')
            .replace(/\\Longleftrightarrow\b/g, '⟺')
            .replace(/\\DYNAMIC\b/g, 'dynamic')
            .replace(/\\ldots\b/g, '...')
            .replace(/\\le\b/g, '≤')
            .replace(/\\botObject\b/g, '⊥_Object') // x~subscript~
            .replace(/{}/g, '')
        ;
        return (mathText === '⊥' || mathText === '⟺')
            ? Str(mathText)
            : pandoc.Emph([Str(mathText)]);
    }
}

pandoc.stdio(action);
